"""
tests/test_forecasting.py — Offline unit tests for the ARIMA forecasting pipeline.

All tests use synthetic data generated by make_synthetic_series() and do NOT
require BigQuery credentials, network access, or a running FastAPI server.
"""
import math
import pytest
import pandas as pd
import numpy as np

from services.forecasting.data_loader import (
    make_synthetic_series,
    load_series,
    DOMAIN_METRICS,
    _train_test_split,
)
from services.forecasting.sarimax_engine import fit_and_forecast
from services.forecasting.evaluator import evaluate
from services.forecasting.visualizer import build_evaluation_chart


# ── data_loader tests ─────────────────────────────────────────────────────────

class TestSyntheticSeries:
    def test_returns_series_result(self):
        result = make_synthetic_series()
        assert result.domain == "retail"
        assert result.metric == "total_retail_sales_millions"
        assert isinstance(result.train, pd.Series)
        assert isinstance(result.test, pd.Series)

    def test_correct_split_lengths(self):
        result = make_synthetic_series(n_obs=60, test_months=12)
        assert len(result.train) == 48
        assert len(result.test) == 12

    def test_train_index_is_datetimeindex(self):
        result = make_synthetic_series()
        assert isinstance(result.train.index, pd.DatetimeIndex)

    def test_no_nan_values(self):
        result = make_synthetic_series()
        assert result.train.isna().sum() == 0
        assert result.test.isna().sum() == 0

    def test_train_precedes_test(self):
        result = make_synthetic_series()
        assert result.train.index[-1] < result.test.index[0]

    def test_weather_synthetic(self):
        result = make_synthetic_series(
            domain="weather",
            metric="avg_monthly_temp_c",
            location_name="Irvine",
        )
        assert result.domain == "weather"
        assert result.location_name == "Irvine"

    def test_too_few_observations_raises(self):
        with pytest.raises(ValueError, match="test months"):
            _train_test_split(pd.Series([1.0, 2.0, 3.0]), test_months=5)


class TestDomainValidation:
    def test_invalid_domain_raises(self):
        with pytest.raises(ValueError, match="Unknown domain"):
            # Bypass BQ by patching; just test validation path
            from unittest.mock import patch
            with patch("services.forecasting.data_loader._get_bq_client"):
                load_series(domain="invalid_domain", metric="cpi")

    def test_domain_metrics_structure(self):
        assert "weather" in DOMAIN_METRICS
        assert "economic" in DOMAIN_METRICS
        assert "retail" in DOMAIN_METRICS
        assert "avg_monthly_temp_c" in DOMAIN_METRICS["weather"]
        assert "cpi" in DOMAIN_METRICS["economic"]
        assert "total_retail_sales_millions" in DOMAIN_METRICS["retail"]


# ── sarimax_engine tests ───────────────────────────────────────────────────────

class TestSARIMAXEngine:
    @pytest.fixture
    def synthetic(self):
        return make_synthetic_series(n_obs=60, test_months=12)

    def test_fit_returns_forecast_result(self, synthetic):
        result = fit_and_forecast(
            train=synthetic.train,
            test_steps=len(synthetic.test),
        )
        assert result.predictions is not None
        assert len(result.predictions) == len(synthetic.test)

    def test_predictions_are_finite(self, synthetic):
        result = fit_and_forecast(train=synthetic.train, test_steps=len(synthetic.test))
        assert all(np.isfinite(v) for v in result.predictions.values)

    def test_confidence_interval_has_correct_columns(self, synthetic):
        result = fit_and_forecast(train=synthetic.train, test_steps=len(synthetic.test))
        assert "lower" in result.conf_int.columns
        assert "upper" in result.conf_int.columns

    def test_confidence_interval_bounds_ordering(self, synthetic):
        result = fit_and_forecast(train=synthetic.train, test_steps=len(synthetic.test))
        # Lower bound should always be <= upper bound
        assert (result.conf_int["lower"] <= result.conf_int["upper"]).all()

    def test_aic_is_finite(self, synthetic):
        result = fit_and_forecast(train=synthetic.train, test_steps=len(synthetic.test))
        assert math.isfinite(result.aic)

    def test_model_order_is_tuple_of_ints(self, synthetic):
        result = fit_and_forecast(train=synthetic.train, test_steps=len(synthetic.test))
        assert len(result.model_order) == 3
        assert all(isinstance(v, int) for v in result.model_order)

    def test_future_forecast_generated(self, synthetic):
        result = fit_and_forecast(
            train=synthetic.train,
            test_steps=len(synthetic.test),
            forecast_steps=6,
        )
        assert result.future_forecast is not None
        assert len(result.future_forecast) == 6

    def test_no_future_forecast_when_steps_zero(self, synthetic):
        result = fit_and_forecast(
            train=synthetic.train,
            test_steps=len(synthetic.test),
            forecast_steps=0,
        )
        assert result.future_forecast is None


# ── evaluator tests ───────────────────────────────────────────────────────────

class TestEvaluator:
    def test_perfect_prediction_gives_zero_error(self):
        idx = pd.date_range("2024-01-01", periods=12, freq="MS")
        actual = pd.Series([100.0] * 12, index=idx)
        metrics = evaluate(actual=actual, predicted=actual.copy())
        assert metrics.rmse == 0.0
        assert metrics.mae == 0.0
        assert metrics.mape == 0.0

    def test_rmse_always_gte_mae(self):
        idx = pd.date_range("2024-01-01", periods=12, freq="MS")
        actual = pd.Series([100.0 + i for i in range(12)], index=idx)
        predicted = pd.Series([95.0 + i for i in range(12)], index=idx)
        metrics = evaluate(actual=actual, predicted=predicted)
        assert metrics.rmse >= metrics.mae

    def test_mape_nan_when_actual_all_zeros(self):
        idx = pd.date_range("2024-01-01", periods=6, freq="MS")
        actual = pd.Series([0.0] * 6, index=idx)
        predicted = pd.Series([1.0] * 6, index=idx)
        metrics = evaluate(actual=actual, predicted=predicted)
        assert math.isnan(metrics.mape)

    def test_metrics_are_non_negative(self):
        idx = pd.date_range("2024-01-01", periods=12, freq="MS")
        actual = pd.Series(np.random.rand(12) * 500, index=idx)
        predicted = pd.Series(np.random.rand(12) * 500, index=idx)
        metrics = evaluate(actual=actual, predicted=predicted)
        assert metrics.rmse >= 0
        assert metrics.mae >= 0

    def test_empty_overlap_raises(self):
        actual = pd.Series([1.0], index=pd.date_range("2024-01-01", periods=1, freq="MS"))
        predicted = pd.Series([1.0], index=pd.date_range("2025-01-01", periods=1, freq="MS"))
        with pytest.raises(ValueError, match="overlapping index"):
            evaluate(actual=actual, predicted=predicted)


# ── visualizer tests ──────────────────────────────────────────────────────────

class TestVisualizer:
    @pytest.fixture
    def chart_inputs(self):
        synth = make_synthetic_series(n_obs=60, test_months=12)
        forecast = fit_and_forecast(train=synth.train, test_steps=len(synth.test))
        return synth, forecast

    def test_returns_non_empty_bytes(self, chart_inputs):
        synth, forecast = chart_inputs
        png_bytes, b64 = build_evaluation_chart(
            train=synth.train,
            actual=synth.test,
            predicted=forecast.predictions,
            conf_int=forecast.conf_int,
            metric=synth.metric,
            domain=synth.domain,
        )
        assert isinstance(png_bytes, bytes)
        assert len(png_bytes) > 0

    def test_bytes_is_valid_png(self, chart_inputs):
        synth, forecast = chart_inputs
        png_bytes, _ = build_evaluation_chart(
            train=synth.train,
            actual=synth.test,
            predicted=forecast.predictions,
            conf_int=forecast.conf_int,
            metric=synth.metric,
            domain=synth.domain,
        )
        # PNG magic number: first 8 bytes
        assert png_bytes[:8] == b"\x89PNG\r\n\x1a\n"

    def test_base64_is_decodable(self, chart_inputs):
        import base64
        synth, forecast = chart_inputs
        _, b64 = build_evaluation_chart(
            train=synth.train,
            actual=synth.test,
            predicted=forecast.predictions,
            conf_int=forecast.conf_int,
            metric=synth.metric,
            domain=synth.domain,
        )
        decoded = base64.b64decode(b64)
        assert len(decoded) > 0

    def test_weather_chart_with_location_name(self, chart_inputs):
        synth, forecast = chart_inputs
        png_bytes, _ = build_evaluation_chart(
            train=synth.train,
            actual=synth.test,
            predicted=forecast.predictions,
            conf_int=forecast.conf_int,
            metric="avg_monthly_temp_c",
            domain="weather",
            location_name="Irvine",
        )
        assert len(png_bytes) > 0

