"""Add retail observations

Revision ID: 253a3e2d90d4
Revises: ff629c0b8967
Create Date: 2026-08-16 20:21:19.432408

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "253a3e2d90d4"
down_revision: str | Sequence[str] | None = "ff629c0b8967"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "retail_observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("naics_code", sa.String(), nullable=False),
        sa.Column("category_name", sa.String(), nullable=True),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("observed_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("naics_code", "observed_at", name="unique_retail_time"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("retail_observations")
    # ### end Alembic commands ###
