"""add unique constraint to weather_observations

Revision ID: 2db4d7ac79ff
Revises: 612bd3b236f3
Create Date: 2026-04-26 22:46:07.235102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2db4d7ac79ff'
down_revision: Union[str, Sequence[str], None] = '612bd3b236f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_api_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('identifier', sa.String(length=100), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('unique_location_time', 'weather_observations', ['location_id', 'observed_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_location_time', 'weather_observations', type_='unique')
    op.drop_table('raw_api_responses')
    # ### end Alembic commands ###
