"""add pressure and humidity

Revision ID: 38aa94cdca20
Revises: 
Create Date: 2026-04-25 18:26:57.678916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38aa94cdca20'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('weather_observations', sa.Column('location_id', sa.Integer(), nullable=True))
    op.add_column('weather_observations', sa.Column('pressure', sa.Float(), nullable=True))
    op.add_column('weather_observations', sa.Column('humidity', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'weather_observations', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weather_observations', type_='foreignkey')
    op.drop_column('weather_observations', 'humidity')
    op.drop_column('weather_observations', 'pressure')
    op.drop_column('weather_observations', 'location_id')
    op.drop_table('locations')
    # ### end Alembic commands ###
