"""add series_name

Revision ID: 612bd3b236f3
Revises: 38aa94cdca20
Create Date: 2026-04-26 20:12:03.435498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '612bd3b236f3'
down_revision: Union[str, Sequence[str], None] = '38aa94cdca20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('economic_observations', sa.Column('series_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'locations', ['latitude', 'longitude'])
    op.alter_column('weather_observations', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('weather_unique_record'), 'weather_observations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('weather_unique_record'), 'weather_observations', ['location_id', 'observed_at'], postgresql_nulls_not_distinct=False)
    # op.alter_column('weather_observations', 'location_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    op.drop_constraint(None, 'locations', type_='unique')
    op.drop_column('economic_observations', 'series_name')
    # ### end Alembic commands ###
