"""add analytics indexes

Revision ID: a50608ea2204
Revises: 4c63fdaddc59
Create Date: 2026-05-26 19:28:58.255322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a50608ea2204'
down_revision: Union[str, Sequence[str], None] = '4c63fdaddc59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_economic_series_time', 'economic_observations', ['series_id', 'observed_at'], unique=False)
    op.create_index('idx_weather_location_time', 'weather_observations', ['location_id', 'observed_at'], unique=False)
    op.create_index('idx_weather_time', 'weather_observations', ['observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_weather_time', table_name='weather_observations')
    op.drop_index('idx_weather_location_time', table_name='weather_observations')
    op.drop_index('idx_economic_series_time', table_name='economic_observations')
    # ### end Alembic commands ###
