"""remove duplicate indexes

Revision ID: ff629c0b8967
Revises: a50608ea2204
Create Date: 2026-05-26 19:32:42.730252

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff629c0b8967"
down_revision: str | Sequence[str] | None = "a50608ea2204"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_economic_series_time"), table_name="economic_observations")
    op.drop_index(op.f("idx_weather_location_time"), table_name="weather_observations")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_weather_location_time"),
        "weather_observations",
        ["location_id", "observed_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_economic_series_time"),
        "economic_observations",
        ["series_id", "observed_at"],
        unique=False,
    )
    # ### end Alembic commands ###
